name: Run end-to-end tests

on: 
  workflow_dispatch:
    inputs:
      denoVersion:
        description: 'Deno Version'     
        required: true
        default: '1.3.2'
      denoWorkerVersion:
        description: 'Deno Worker Version'
        required: true
        default: 'preview'

jobs:
  e2e:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    name: ${{ matrix.os }} end-to-end
    runs-on: ${{ matrix.os }}

    steps:

    - uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ github.event.inputs.denoVersion }}

    - run: |
        if ["$MATRIX_OS" == "windows-latest"]; then
          export DENOFUNC_COMMAND=denofunc.cmd
        else
          export DENOFUNC_COMMAND=denofunc
        fi
        export PATH=$HOME/.deno/bin:$PATH
        echo $PATH
        deno install --allow-run --allow-read --allow-write --allow-net --unstable --force --name=denofunc https://raw.githubusercontent.com/anthonychu/azure-functions-deno-worker/${{ github.event.inputs.denoWorkerVersion }}/denofunc.ts
        $DENOFUNC_COMMAND init
        ls -la
      shell: bash
      env:
        MATRIX_OS: ${{ matrix.os }}