name: Run end-to-end tests

on: 
  workflow_dispatch:
    inputs:
      denoVersion:
        description: 'Deno Version'     
        required: true
        default: '1.3.1'
      denoWorkerVersion:
        description: 'Deno Worker Version'
        required: true
        default: 'preview'

jobs:
  e2eLinux:
    name: Linux end-to-end
    runs-on: ubuntu-latest

    steps:

    - uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ github.event.inputs.denoVersion }}

    - run: |
        export PATH=$GITHUB_WORKSPACE/.deno/bin:$PATH
        deno install --allow-run --allow-read --allow-write --allow-net --unstable --force --name=denofunc https://raw.githubusercontent.com/anthonychu/azure-functions-deno-worker/${{ github.event.inputs.denoWorkerVersion }}/denofunc.ts
        denofunc init
        ls -la